revert varnish images to original repo for correct versioning
drpayyne/warden-multi-arch pull request #32
Opened 2022-07-06 11:25 UTC by erlisdhima

2022-07-20 13:16 UTC, drpayyne requested changes

2022-07-20 13:16 UTC, drpayyne commented on .github/workflows/docker-image-varnish.yml
> +          - "7.1"
Should the versions be `xy` instead of `x.y`?

2022-07-20 13:16 UTC, drpayyne commented on images/varnish/Dockerfile
> +    && dnf module disable -y varnish \
What's the reason for disabling this module?

2022-07-20 13:30 UTC, erlisdhima commented on .github/workflows/docker-image-varnish.yml
> +          - "7.1"
The `.` is removed in this line https://github.com/drpayyne/warden-multi-arch/pull/32/files#diff-876f88dab6320ed343f8b53555ad6366f7c787f34b0daa66cba4ced9fd5216fcR41

2022-07-20 13:40 UTC, erlisdhima commented on images/varnish/Dockerfile
> +    && dnf module disable -y varnish \
<img width="847" alt="image" src="https://user-images.githubusercontent.com/7734108/179996650-e2411b74-7c29-4c0b-ab9a-b2d43d2080a2.png">
More info here: https://varnish-cache.org/docs/trunk/installation/install_redhat.html

2022-08-04 20:21 UTC, drpayyne commented on images/varnish/Dockerfile
> +    && dnf module disable -y varnish \
Thank you!

2022-08-04 20:21 UTC, drpayyne commented
Merging now!

2022-08-04 20:22 UTC, merged